config/routes.rb
Rails.application.routes.draw do
  get 'wallet_dashboard/index'
  
  root 'wallet_dashboard#index'

  resources :wallet_transactions

end

app/models/wallet_transaction.rb
class WalletTransaction < ActiveRecord::Base
  
  def self.total_wallet_transactions
    self.count
  end
  
  
  def self.income
    self.all.select {|t| t.Category_Type =="Income"}
  end

  def self.cost
    self.all.select {|t| t.Category_Type == "Cost"}
    
  end
  
  def self.wallet_amount
    costs = cost.reduce(0) {|sum, cost| sum + cost.Amount}
    incomes = income.reduce(0) {|sum, income| sum + income.Amount}
    incomes - costs
  end
  
  
  
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wallet_dashboard_controller.rb
class WalletDashboardController < ApplicationController
  def index
  end
  
  def index
    @wallet_total = WalletTransaction.wallet_amount
    @total_transactions = WalletTransaction.total_wallet_transactions

  end
  
  
end

app/controllers/wallet_transactions_controller.rb
class WalletTransactionsController < ApplicationController
  before_action :set_wallet_transaction, only: [:show, :edit, :update, :destroy]

  # GET /wallet_transactions
  # GET /wallet_transactions.json
  def index
    @wallet_transactions = WalletTransaction.all
  end

  # GET /wallet_transactions/1
  # GET /wallet_transactions/1.json
  def show
  end

  # GET /wallet_transactions/new
  def new
    @wallet_transaction = WalletTransaction.new
  end

  # GET /wallet_transactions/1/edit
  def edit
  end

  # POST /wallet_transactions
  # POST /wallet_transactions.json
  def create
    @wallet_transaction = WalletTransaction.new(wallet_transaction_params)

    respond_to do |format|
      if @wallet_transaction.save
        format.html { redirect_to @wallet_transaction, notice: 'Wallet transaction was successfully created.' }
        format.json { render :show, status: :created, location: @wallet_transaction }
      else
        format.html { render :new }
        format.json { render json: @wallet_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallet_transactions/1
  # PATCH/PUT /wallet_transactions/1.json
  def update
    respond_to do |format|
      if @wallet_transaction.update(wallet_transaction_params)
        format.html { redirect_to @wallet_transaction, notice: 'Wallet transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallet_transaction }
      else
        format.html { render :edit }
        format.json { render json: @wallet_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallet_transactions/1
  # DELETE /wallet_transactions/1.json
  def destroy
    @wallet_transaction.destroy
    respond_to do |format|
      format.html { redirect_to wallet_transactions_url, notice: 'Wallet transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet_transaction
      @wallet_transaction = WalletTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wallet_transaction_params
      params.require(:wallet_transaction).permit(:Category_Type, :Transaction_Description, :Amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wallet_dashboard_helper.rb
module WalletDashboardHelper
end

app/helpers/wallet_transactions_helper.rb
module WalletTransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WalletApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wallet_dashboard/index.html.erb
	
<h1>Wallet Dashboard</h1>



<p>Your current amount in wallet: $<%=@wallet_total%></p>
<% if @wallet_total > 25 %>
  <p>Wallet contains enough money for spending</p>
<%  elsif @wallet_total == 25%>
  <p>Warning: You are about to go broke - only $25 left!</p>
 <% elsif @wallet_total < 25  && @wallet_total >= 1%>
  <p>Warning: Need to stop spending money, wallet is almost empty!</p>
  <% elsif @wallet_total < 1%>
   <p>WALLET IS NOW EMPTY!</p>
  <p>
<% end %>
 
<p>Number of wallet transactions:<%=@total_transactions%> </p>


<p><%= link_to 'New Wallet transaction', new_wallet_transaction_path %>

&nbsp;&nbsp;<%= link_to 'Wallet Transactions', wallet_transactions_path %></p>

app/views/wallet_transactions/_form.html.erb
<%= form_for(@wallet_transaction) do |f| %>
  <% if @wallet_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wallet_transaction.errors.count, "error") %> prohibited this wallet_transaction from being saved:</h2>

      <ul>
      <% @wallet_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Category_Type %><br>
    <%= f.select :Category_Type, options_for_select([["Income"],["Cost"]])%>
  </div>
  
  
  <div class="field">
    <%= f.label :Transaction_Description %><br>
    <%= f.text_area :Transaction_Description %>
  </div>
  <div class="field">
    <%= f.label :Amount %><br>
    <%= f.number_field :Amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wallet_transactions/edit.html.erb
<h1>Editing Wallet Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @wallet_transaction %> |
<%= link_to 'Back', wallet_transactions_path %>

app/views/wallet_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wallet Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Category type</th>
      <th>Transaction description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wallet_transactions.each do |wallet_transaction| %>
      <tr>
        <td><%= wallet_transaction.Category_Type %></td>
        <td><%= wallet_transaction.Transaction_Description %></td>
        <td><%= wallet_transaction.Amount %></td>
        <td><%= link_to 'Show', wallet_transaction %></td>
        <td><%= link_to 'Edit', edit_wallet_transaction_path(wallet_transaction) %></td>
        <td><%= link_to 'Destroy', wallet_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>Your current amount in wallet: $<%=WalletTransaction.wallet_amount%></p>

<%= link_to 'New Wallet transaction', new_wallet_transaction_path %>&nbsp;&nbsp;
<%= link_to 'Dashboard', root_path %></p>

app/views/wallet_transactions/new.html.erb
<h1>New Wallet Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', wallet_transactions_path %>

app/views/wallet_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category type:</strong>
  <%= @wallet_transaction.Category_Type %>
</p>

<p>
  <strong>Transaction description:</strong>
  <%= @wallet_transaction.Transaction_Description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @wallet_transaction.Amount %>
</p>

<%= link_to 'Edit', edit_wallet_transaction_path(@wallet_transaction) %> |
<%= link_to 'Back', wallet_transactions_path %>